"""create all tables

Revision ID: 0d16aa5bf7f9
Revises: 
Create Date: 2026-03-17 10:50:33.132311

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0d16aa5bf7f9'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agg_audio_profiles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cluster_id', sa.Integer(), nullable=False),
    sa.Column('cluster_label', sa.String(length=50), nullable=False),
    sa.Column('centroid_tempo', sa.Float(), nullable=False),
    sa.Column('centroid_energy', sa.Float(), nullable=False),
    sa.Column('centroid_valence', sa.Float(), nullable=False),
    sa.Column('centroid_danceability', sa.Float(), nullable=False),
    sa.Column('track_count', sa.Integer(), nullable=False),
    sa.Column('snapshot_date', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dim_album',
    sa.Column('album_key', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('spotify_album_id', sa.String(length=62), nullable=False),
    sa.Column('album_name', sa.String(length=500), nullable=False),
    sa.Column('album_type', sa.String(length=20), nullable=True),
    sa.Column('release_date', sa.Date(), nullable=True),
    sa.Column('total_tracks', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('album_key')
    )
    op.create_index(op.f('ix_dim_album_spotify_album_id'), 'dim_album', ['spotify_album_id'], unique=True)
    op.create_table('dim_artist',
    sa.Column('artist_key', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('spotify_artist_id', sa.String(length=62), nullable=False),
    sa.Column('artist_name', sa.String(length=500), nullable=False),
    sa.Column('popularity', sa.Integer(), nullable=True),
    sa.Column('followers', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('artist_key')
    )
    op.create_index(op.f('ix_dim_artist_spotify_artist_id'), 'dim_artist', ['spotify_artist_id'], unique=True)
    op.create_table('dim_date',
    sa.Column('date_key', sa.Integer(), nullable=False),
    sa.Column('full_date', sa.Date(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('quarter', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('month_name', sa.String(length=10), nullable=False),
    sa.Column('week_of_year', sa.Integer(), nullable=False),
    sa.Column('day_of_week', sa.Integer(), nullable=False),
    sa.Column('is_weekend', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('date_key'),
    sa.UniqueConstraint('full_date')
    )
    op.create_table('dim_genre',
    sa.Column('genre_key', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('genre_name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('genre_key')
    )
    op.create_index(op.f('ix_dim_genre_genre_name'), 'dim_genre', ['genre_name'], unique=True)
    op.create_table('pipeline_run_log',
    sa.Column('run_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('pipeline_name', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('rows_extracted', sa.Integer(), nullable=False),
    sa.Column('rows_loaded', sa.Integer(), nullable=False),
    sa.Column('errors_json', sa.Text(), nullable=True),
    sa.Column('duration_seconds', sa.Float(), nullable=False),
    sa.Column('endpoint_statuses_json', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('run_id')
    )
    op.create_index(op.f('ix_pipeline_run_log_pipeline_name'), 'pipeline_run_log', ['pipeline_name'], unique=False)
    op.create_table('agg_genre_stats',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('genre_key', sa.Integer(), nullable=False),
    sa.Column('period', sa.String(length=10), nullable=False),
    sa.Column('period_date', sa.Date(), nullable=False),
    sa.Column('track_count', sa.Integer(), nullable=False),
    sa.Column('avg_popularity', sa.Float(), nullable=False),
    sa.Column('avg_danceability', sa.Float(), nullable=False),
    sa.Column('avg_energy', sa.Float(), nullable=False),
    sa.Column('avg_tempo', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['genre_key'], ['dim_genre.genre_key'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agg_genre_stats_genre_key'), 'agg_genre_stats', ['genre_key'], unique=False)
    op.create_table('bridge_artist_genre',
    sa.Column('artist_key', sa.Integer(), nullable=False),
    sa.Column('genre_key', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['artist_key'], ['dim_artist.artist_key'], ),
    sa.ForeignKeyConstraint(['genre_key'], ['dim_genre.genre_key'], ),
    sa.PrimaryKeyConstraint('artist_key', 'genre_key')
    )
    op.create_table('dim_track',
    sa.Column('track_key', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('spotify_track_id', sa.String(length=62), nullable=False),
    sa.Column('track_name', sa.String(length=500), nullable=False),
    sa.Column('album_key', sa.Integer(), nullable=True),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('explicit', sa.Boolean(), nullable=True),
    sa.Column('isrc', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['album_key'], ['dim_album.album_key'], ),
    sa.PrimaryKeyConstraint('track_key')
    )
    op.create_index(op.f('ix_dim_track_spotify_track_id'), 'dim_track', ['spotify_track_id'], unique=True)
    op.create_table('agg_trending_tracks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('track_key', sa.Integer(), nullable=False),
    sa.Column('window_start', sa.Date(), nullable=False),
    sa.Column('window_end', sa.Date(), nullable=False),
    sa.Column('popularity_delta', sa.Integer(), nullable=False),
    sa.Column('velocity', sa.Float(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['track_key'], ['dim_track.track_key'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agg_trending_tracks_track_key'), 'agg_trending_tracks', ['track_key'], unique=False)
    op.create_table('bridge_track_artist',
    sa.Column('track_key', sa.Integer(), nullable=False),
    sa.Column('artist_key', sa.Integer(), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['artist_key'], ['dim_artist.artist_key'], ),
    sa.ForeignKeyConstraint(['track_key'], ['dim_track.track_key'], ),
    sa.PrimaryKeyConstraint('track_key', 'artist_key')
    )
    op.create_table('fact_audio_features',
    sa.Column('audio_feature_key', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('track_key', sa.Integer(), nullable=False),
    sa.Column('danceability', sa.Float(), nullable=True),
    sa.Column('energy', sa.Float(), nullable=True),
    sa.Column('loudness', sa.Float(), nullable=True),
    sa.Column('speechiness', sa.Float(), nullable=True),
    sa.Column('acousticness', sa.Float(), nullable=True),
    sa.Column('instrumentalness', sa.Float(), nullable=True),
    sa.Column('liveness', sa.Float(), nullable=True),
    sa.Column('valence', sa.Float(), nullable=True),
    sa.Column('tempo', sa.Float(), nullable=True),
    sa.Column('tempo_category', sa.String(length=10), nullable=True),
    sa.Column('time_signature', sa.Integer(), nullable=True),
    sa.Column('key', sa.Integer(), nullable=True),
    sa.Column('mode', sa.Integer(), nullable=True),
    sa.Column('snapshot_date_key', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['snapshot_date_key'], ['dim_date.date_key'], ),
    sa.ForeignKeyConstraint(['track_key'], ['dim_track.track_key'], ),
    sa.PrimaryKeyConstraint('audio_feature_key')
    )
    op.create_index(op.f('ix_fact_audio_features_track_key'), 'fact_audio_features', ['track_key'], unique=False)
    op.create_table('fact_track_popularity',
    sa.Column('popularity_key', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('track_key', sa.Integer(), nullable=False),
    sa.Column('date_key', sa.Integer(), nullable=False),
    sa.Column('popularity', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=10), nullable=False),
    sa.ForeignKeyConstraint(['date_key'], ['dim_date.date_key'], ),
    sa.ForeignKeyConstraint(['track_key'], ['dim_track.track_key'], ),
    sa.PrimaryKeyConstraint('popularity_key')
    )
    op.create_index(op.f('ix_fact_track_popularity_date_key'), 'fact_track_popularity', ['date_key'], unique=False)
    op.create_index(op.f('ix_fact_track_popularity_track_key'), 'fact_track_popularity', ['track_key'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_fact_track_popularity_track_key'), table_name='fact_track_popularity')
    op.drop_index(op.f('ix_fact_track_popularity_date_key'), table_name='fact_track_popularity')
    op.drop_table('fact_track_popularity')
    op.drop_index(op.f('ix_fact_audio_features_track_key'), table_name='fact_audio_features')
    op.drop_table('fact_audio_features')
    op.drop_table('bridge_track_artist')
    op.drop_index(op.f('ix_agg_trending_tracks_track_key'), table_name='agg_trending_tracks')
    op.drop_table('agg_trending_tracks')
    op.drop_index(op.f('ix_dim_track_spotify_track_id'), table_name='dim_track')
    op.drop_table('dim_track')
    op.drop_table('bridge_artist_genre')
    op.drop_index(op.f('ix_agg_genre_stats_genre_key'), table_name='agg_genre_stats')
    op.drop_table('agg_genre_stats')
    op.drop_index(op.f('ix_pipeline_run_log_pipeline_name'), table_name='pipeline_run_log')
    op.drop_table('pipeline_run_log')
    op.drop_index(op.f('ix_dim_genre_genre_name'), table_name='dim_genre')
    op.drop_table('dim_genre')
    op.drop_table('dim_date')
    op.drop_index(op.f('ix_dim_artist_spotify_artist_id'), table_name='dim_artist')
    op.drop_table('dim_artist')
    op.drop_index(op.f('ix_dim_album_spotify_album_id'), table_name='dim_album')
    op.drop_table('dim_album')
    op.drop_table('agg_audio_profiles')
    # ### end Alembic commands ###
