"""increase name column lengths to 1000

Revision ID: 766a59bb6f78
Revises: 0d16aa5bf7f9
Create Date: 2026-03-17 10:54:04.414623

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "766a59bb6f78"
down_revision: str | None = "0d16aa5bf7f9"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "dim_album",
        "album_name",
        existing_type=sa.VARCHAR(length=500),
        type_=sa.String(length=1000),
        existing_nullable=False,
    )
    op.alter_column(
        "dim_artist",
        "artist_name",
        existing_type=sa.VARCHAR(length=500),
        type_=sa.String(length=1000),
        existing_nullable=False,
    )
    op.alter_column(
        "dim_track",
        "track_name",
        existing_type=sa.VARCHAR(length=500),
        type_=sa.String(length=1000),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "dim_track",
        "track_name",
        existing_type=sa.String(length=1000),
        type_=sa.VARCHAR(length=500),
        existing_nullable=False,
    )
    op.alter_column(
        "dim_artist",
        "artist_name",
        existing_type=sa.String(length=1000),
        type_=sa.VARCHAR(length=500),
        existing_nullable=False,
    )
    op.alter_column(
        "dim_album",
        "album_name",
        existing_type=sa.String(length=1000),
        type_=sa.VARCHAR(length=500),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
